spanish = {
    "ERROR_DATE_FORMAT": "La fecha debe de seguir el siguiente formato: YYYY-MM-DDTHH:mm:ss",
    "ERROR_NULL_PAYMENT_CODE": "El código de pago no existe",
    "ERROR_OFFER_NOT_FOUND": "La oferta no existe",
    "ERROR_OFFER_NOT_OWNER": "No eres el propietario de la oferta",
    "ERROR_PAYMENT_COMPLETED": "El pago ya ha sido completado o la oferta ya ha finalizado",
    "ERROR_PAYPAL_NOT_RESPONSE": "No hay respuesta de PayPal",
    "ERROR_TOKEN_NOT_TAKEN": "No se ha pasado el token",
    "ERROR_PAYPAL_CREDENTIALS": "Las credenciales de PayPal no son correctas. O bien la cuenta no existe o bien no tienes una asociada en tu perfil.",
    "ERROR_BRAINTREE_CREDENTIALS": "Las credenciales de Braintree no son correctas",
    "ERROR_PAYMENT_NOT_RESPONSE": "No hay respuesta del pago",
    "ERROR_OFFER_PAST_DATE": "La oferta ha caducado",
    "ERROR_STATUS_NOT_PROVIDED": "El estado de la oferta no ha sido aportado",
    "ERROR_STATUS_NOT_CHANGED": "El estado de la oferta no ha sido modificado",
    "ERROR_BRAINTREE_ENV_NOT_SET": "El entorno de Braintree no ha sido configurado",
    "ERROR_TRANSACTION_STATUS_NOT_ALLOWED": "Este cambio de estado no está permitido.",
    "ERROR_USER_NOT_AUTHORIZED": "Usuario no autorizado",
    "ERROR_DESCRIPTION_NOT_PROVIDED": "No se ha suministrado la descripción",
    "ERROR_DATE_NOT_PROVIDED": "No se ha suministrado la fecha",
    "ERROR_DATE_PAST": "La fecha no puede ser pasada",
    "ERROR_PAYMENTPACKAGE_NOT_PROVIDED": "No se ha suministrado un paquete de pago",
    "ERROR_PAYMENTPACKAGE_NOT_FOUND": "El paquete de pago no existe",
    "ERROR_HOURS_NOT_PROVIDED": "No se ha suministrado las horas",
    "ERROR_HOURS_BAD_PROVIDED": "El valor de horas no es válido",
    "ERROR_PRICE_NOT_PROVIDED": "No se ha suministrado el precio",
    "ERROR_PRICE_BELOW_MUNIMUM": "El valor del precio está por debajo del mínimo",
    "ERROR_EVENTLOCATION_NOT_PROVIDED": "No se ha suministrado la localización del evento",
    "ERROR_EVENTLOCATION_NOT_FOUND": "La localización del evento no existe",
    "ERROR_EVENTLOCATION_CAN_NOT_ASSIGNED": "No puedes asignar esta localización",
    "ERROR_CUSTOMER_NOT_FOUND": "El cliente no existe",
    "ERROR_NO_USER": "No hay usuarios de este tipo",
    "ERROR_NOT_ALLOWED_USER": "No tienes los privilegios para ver esta página o realizar esta acción.",
    "ERROR_NOT_LOGGED_IN": "Debes estar autenticado para entrar en este sitio.",
    "ERROR_NOT_OFFER_OWNER": "La oferta no te pertence",
    "ERROR_NOT_A_CUSTOMER": "No eres el cliente adecuado, y por tanto no puedes estar en este sitio.",
    "ERROR_NOT_AN_ARTIST": "No eres el artista adeacuado, y por tanto no puedes estar en este sitio.",
    "ERROR_NO_ARTIST_FOUND": "El artista que buscas no existe.",
    "ERROR_NULL_ARTIST": "Debes especificar el artista que va a introducir el código de pago.",
    "ERROR_NO_PAYMENTCODE_FOUND": "No se pudo encontrar el código de pago que buscas.",
    "ERROR_NO_DATA_GIVEN": "El formulario no tiene datos.",
    "ERROR_NO_MATCHING_LANGUAGE": "El idioma que has escogido no esta disponible.",
    "ERROR_NO_GIVEN_LANGUAGE": "Debes indicar un idioma al que cambiar.",
    "ERROR_RESPONSE": "No hay respuesta desde Paypal",
    "ERROR_CREDENTIAL": "Error de credenciales de Paypal",
    "ERROR_CREDENTIAL_BRAINTREE": "Error de credencial Braintree",
    "ERROR_DATE_PAYMENT" : "Paypal no puede procesar un pago realizado hace mas de 29 dias",
    "ERROR_REASON_NOT_PROVIDED": "No se ha suministrado una razón",
    "ERROR_PAYMENTCODE_TOO_LONG": "El código de pago es demasiado largo",
    "ERROR_DATE_NOT_AVAILABLE": "El artista no puede actuar para la fecha indicada",
    "ERROR_PAYPAL_PRICE_REACH": "Límite de precio en Paypal alcanzado",
    "ERROR_REASON_TOO_LONG": "La razón es demasiado larga.",
    "ERROR_INVALID_PAYMENTCODE": "El código de pago no es válido.",
}

english = {
    "ERROR_REASON_TOO_LONG": "The reason is too long.",
    "ERROR_PAYMENTCODE_TOO_LONG": "Payment code is too long.",
    "ERROR_DATE_FORMAT": "Date must follow this format: YYYY-MM-DDTHH:mm:ss",
    "ERROR_NULL_PAYMENT_CODE": "Payment code hasn't exist",
    "ERROR_OFFER_NOT_FOUND": "Offer don't exist",
    "ERROR_OFFER_NOT_OWNER": "You aren't owner of this offer",
    "ERROR_PAYMENT_COMPLETED": "Payment has been completed already or it's a past offer",
    "ERROR_PAYPAL_NOT_RESPONSE": "There isn't PayPal response",
    "ERROR_TOKEN_NOT_TAKEN": "Token hasn't been taken",
    "ERROR_PAYPAL_CREDENTIALS": "Incorrect PayPal credentials. Either it doesn't exist or you haven't given one in your profile.",
    "ERROR_BRAINTREE_CREDENTIALS": "Incorrect Braintree credentials",
    "ERROR_PAYMENT_NOT_RESPONSE": "There isn't payment response",
    "ERROR_OFFER_PAST_DATE": "The offer has expired.",
    "ERROR_STATUS_NOT_PROVIDED": "Offer status hasn't been provided",
    "ERROR_STATUS_NOT_CHANGED": "Offer status hasn't been changed",
    "ERROR_BRAINTREE_ENV_NOT_SET": "Braintree enviroment hasn't been set up",
    "ERROR_TRANSACTION_STATUS_NOT_ALLOWED": "This status transaction is not allowed.",
    "ERROR_USER_NOT_AUTHORIZED": "User isn't authorized",
    "ERROR_DESCRIPTION_NOT_PROVIDED": "Description hasn't provided",
    "ERROR_DATE_NOT_PROVIDED": "Date hasn't provided",
    "ERROR_DATE_PAST": "Date can't be pass",
    "ERROR_PAYMENTPACKAGE_NOT_PROVIDED": "Payment packege hasn't provided",
    "ERROR_PAYMENTPACKAGE_NOT_FOUND": "Payment packages doesn't exist",
    "ERROR_HOURS_NOT_PROVIDED": "Hours hasn't provided",
    "ERROR_HOURS_BAD_PROVIDED": "Hours value isn't valid",
    "ERROR_PRICE_NOT_PROVIDED": "Price hasn't provided",
    "ERROR_PRICE_BELOW_MUNIMUM": "Price value is below of minimum price",
    "ERROR_EVENTLOCATION_NOT_PROVIDED": "Event location hasn't provided",
    "ERROR_EVENTLOCATION_NOT_FOUND": "Event location hasn't exist",
    "ERROR_EVENTLOCATION_CAN_NOT_ASSIGNED": "Event location can't be assigned",
    "ERROR_CUSTOMER_NOT_FOUND": "Customer doesn't exist",
    "ERROR_NO_USER": "There are no users of this type",
    "ERROR_NOT_LOGGED_IN": "You must be logged in to access this page.",
    "ERROR_NOT_AN_ARTIST": "You are not the artist we was waiting for, and therefore you cannot be here.",
    "ERROR_NOT_OFFER_OWNER": "You are not the owner of the offer",
    "ERROR_NOT_A_CUSTOMER": "You are not the customer we was waiting for, and therefore you cannot be here.",
    "ERROR_NO_ARTIST_FOUND": "The artist you are searching for does not exist.",
    "ERROR_NO_PAYMENTCODE_FOUND": "The payment code could not be found.",
    "ERROR_NULL_ARTIST": "You must give the artist that will accept the payment code.",
    "ERROR_NOT_ALLOWED_USER": "You lack the privileges to view this page or perform this action.",
    "ERROR_NO_DATA_GIVEN": "The form has no data.",
    "ERROR_NO_MATCHING_LANGUAGE": "This language is not available.",
    "ERROR_NO_GIVEN_LANGUAGE": "You must choose a language.",
    "ERROR_RESPONSE": "No response from Paypal",
    "ERROR_CREDENTIAL": "Credential error with paypal",
    "ERROR_CREDENTIAL_BRAINTREE": "Credential error with paypal",
    "ERROR_DATE_PAYMENT" : "Paypal cannot process a payment more than 29 days old",
    "ERROR_REASON_NOT_PROVIDED": "Reason isn't provided",
    "ERROR_DATE_NOT_AVAILABLE": "Artist can't act for provided date",
    "ERROR_PAYPAL_PRICE_REACH": "Paypal price limit reached",
    "ERROR_INVALID_PAYMENTCODE": "The payment code is invalid.",
}


def translate(keyLanguage: str, keyToTranslate: str):
    translations = {
        "es": spanish,
        "en": english
    }

    return {"error": translations[keyLanguage][keyToTranslate]}
