spanish = {
    "ERROR_EMPTY_JSON": "El formulario no puede estar vacío.",
    "ERROR_INVALID_PAYPAL_ACCOUNT": "Cuenta de Paypal inválida.",
    "ERROR_EMPTY_FIRST_NAME": "El nombre no puede estar vacío.",
    "ERROR_EMPTY_LAST_NAME": "Los apellidos no pueden estar vacíos.",
    "ERROR_PHONE_MUST_BE_NUMBER": "El teléfono debe ser un número",
    "ERROR_PHONE_LENGTH_9": "El teléfono debe tener 9 dígitos.",
    "ERROR_FIRST_NAME_LENGTH": "El nombre es demasiado corto.",
    "ERROR_LAST_NAME_LENGTH": "Los apellidos son demasiado cortos.",
    "ERROR_INVALID_PHOTO_URL_HTTP": "Url invalida. La foto debe comenzar con http o https",
    "ERROR_INVALID_PHOTO_URL_ENDFORMAT": "Url invalida. La foto debe terminar con una extensión de imagen.",
    "ERROR_NO_ARTISTIC_NAME": "No has introducido un nombre artistico.",
    "ERROR_NOTFOUND_PORTFOLIO": "No se encuentra el portfolio",
    "ERROR_EMPTY_USERNAME": "El usuario no debe estar vacío.",
    "ERROR_EMPTY_PASSWORD": "La contraseña no puede estar vacía.",
    "ERROR_EMPTY_CONFIRM_PASSWORD": "La confirmación de la contraseña no puede estar vacía.",
    "ERROR_PASSWORD_&_CONFIRM_MUST_BE_EQUALS": "La contraseña y su confirmación deben coincidir.",
    "ERROR_PASSWORD_SIMILAR_USERNAME": "La contraseña no debe ser similar al usuario.",
    "ERROR_PASSWORD_SIMILAR_EMAIL": "La contraseña no debe ser similar al email.",
    "ERROR_PASSWORD_SIMILAR_FIRST_NAME": "La contraseña no debe ser simiar al nombre.",
    "ERROR_PASSWORD_SIMILAR_LAST_NAME": "La contraseña no debe ser similar al apellido.",
    "ERROR_PASSWORD_MUST_BE_COMPLEX": "La contraseña debe ser compleja.",
    "ERROR_PASSWORD_IS_TOO_SHORT": "La contraseña es demasiado corta.",
    "ERROR_USERNAME_IN_USE": "El usuario ya existe.",
    "ERROR_EMPTY_FORM": "El formulario no puede estar vacío.",
    "ERROR_EMPTY_EMAIL": "El email no puede estar vacío.",
    "ERROR_EMAIL_IN_USE": "El email ya está en uso.",
    "ERROR_EMAIL_IS_TOO_SHORT": "El email es demasiado corto.",
    "ERROR_EMAIL_INVALID": "Email invalido",
    "ERROR_MUST_LOGGED_OUT": "Debes estar deslogueado para completar esta acción.",
    "ERROR_IT_ISNT_YOUR_PERSONAL_INFO": "Solo puedes cambiar tu información personal",
    "ERROR_ARTIST_NOT_LOGGED": "Permiso denegado.",
    "ERROR_FIRST_NAME_SPECIAL_CHARACTERS": "El nombre no puede contener caracteres especiales ni números.",
    "ERROR_LAST_NAME_SPECIAL_CHARACTERS": "Los apellidos no pueden contener caracteres especiales ni números.",
    "ERROR_EMPTY_ARTISTIC_NAME": "El nombre artistico debe ser obligatorio.",
    "ERROR_ARTISTIC_NAME_ALREADY_EXISTS": "El nombre artistico ya existe.",

    "ERROR_MAX_LENGTH_FIRST_NAME": "El tamaño del nombre no puede ser mayor que 30",
    "ERROR_MAX_LENGTH_LAST_NAME": "El tamaño de los apellidos no puede ser mayor que 150",
    "ERROR_NOT_LOGGED_IN": "Debes estar autenticado para entrar en este sitio.",
    "ERROR_NOT_AN_ARTIST": "No eres un artista, y por tanto no puedes estar en este sitio.",
    "ERROR_NO_ARTIST_FOUND": "El artista que buscas no existe.",
    "ERROR_OFFER_NOT_OWNED": "Esta oferta no te pertenece.",
    "ERROR_OFFER_NOT_FOUND": "La oferta que buscas no existe.",
    "ERROR_NO_DATA_GIVEN": "El formulario no tiene datos.",
    "ERROR_NO_MATCHING_LANGUAGE": "El idioma que has escogido no esta disponible.",
    "ERROR_ACTOR_NOT_FOUND": "El actor que buscas no existe.",
    "ERROR_NO_GIVEN_LANGUAGE": "Debes indicar un idioma al que cambiar.",
    "ERROR_STRING_TOO_LONG": "La cadena de caracteres es demasiado larga.",
    "ERROR_URL_TOO_LONG": "La URL es demasiado larga. El límite es 500 caracteres.",
    "ERROR_ARTISTICNAME_TOO_LONG": "El nombre artístico es demasiado largo.",
    "ERROR_EMAIL_TOO_LONG": "El email es demasiado largo.",
    "ERROR_USERNAME_TOO_LONG": "El usuario es demasiado largo.",
    "ERROR_PASSWORD_TOO_LONG": "La contraseña es demasiado larga.",
    "ERROR_PAYPAL_TOO_LONG": "La dirección de Paypal es demasiado larga.",

}

english = {
    "ERROR_PAYPAL_TOO_LONG": "The paypal account is too long.",
    "ERROR_PASSWORD_TOO_LONG": "The password is too long.",
    "ERROR_USERNAME_TOO_LONG": "The username is too long",
    "ERROR_EMAIL_TOO_LONG": "Email is too long",
    "ERROR_ARTISTICNAME_TOO_LONG": "The artistic name is too long.",
    "ERROR_URL_TOO_LONG": "The URL is too long. Limit is 500 characters.",
    "ERROR_STRING_TOO_LONG": "The string is too long",
    "ERROR_EMPTY_JSON": "Form is not valid.",
    "ERROR_INVALID_PAYPAL_ACCOUNT": "Invalid paypal account.",
    "ERROR_EMPTY_FIRST_NAME": "First name can't be empty.",
    "ERROR_EMPTY_LAST_NAME": "Last name can't be empty.",
    "ERROR_PHONE_MUST_BE_NUMBER": "Phone must be a number.",
    "ERROR_PHONE_LENGTH_9": "Phone must be 9 digits.",
    "ERROR_FIRST_NAME_LENGTH": "First name is too short.",
    "ERROR_LAST_NAME_LENGTH": "Last name is too short.",
    "ERROR_INVALID_PHOTO_URL_HTTP": "Invalid photo url, the photo must start with http.",
    "ERROR_INVALID_PHOTO_URL_ENDFORMAT": "Invalid photo url, the photo must end with an image extension.",
    "ERROR_NO_ARTISTIC_NAME": "You did not submit an artistic name.",
    "ERROR_NOTFOUND_PORTFOLIO": "Portfolio not found.",
    "ERROR_EMPTY_USERNAME": "Username field not provided.",
    "ERROR_EMPTY_PASSWORD": "Password field not provided.",
    "ERROR_EMPTY_CONFIRM_PASSWORD": "Confirm password field not provided.",
    "ERROR_PASSWORD_&_CONFIRM_MUST_BE_EQUALS": "Password & confirmation must match.",
    "ERROR_PASSWORD_SIMILAR_USERNAME": "Password can't be similar to your username",
    "ERROR_PASSWORD_SIMILAR_EMAIL": "Password can't be similar to your email.",
    "ERROR_PASSWORD_SIMILAR_FIRST_NAME": "Password can't be similar to the first name.",
    "ERROR_PASSWORD_SIMILAR_LAST_NAME": "Password can't be similar to the last name.",
    "ERROR_PASSWORD_MUST_BE_COMPLEX": "Password must be complex.",
    "ERROR_PASSWORD_IS_TOO_SHORT": "Password is too short.",
    "ERROR_USERNAME_IN_USE": "Username already in use.",
    "ERROR_EMPTY_FORM": "Empty form is not valid.",
    "ERROR_EMPTY_EMAIL": "Email field not provided.",
    "ERROR_EMAIL_IN_USE": "Email already in use.",
    "ERROR_EMAIL_IS_TOO_SHORT": "Email is too short",
    "ERROR_EMAIL_INVALID": "Invalid email",
    "ERROR_MUST_LOGGED_OUT": "You must be unlogged to do this action.",
    "ERROR_IT_ISNT_YOUR_PERSONAL_INFO": "You can only change your personal info.",
    "ERROR_ARTIST_NOT_LOGGED": "Permission denied.",
    "ERROR_FIRST_NAME_SPECIAL_CHARACTERS": "First name can't contain special characters & numbers.",
    "ERROR_LAST_NAME_SPECIAL_CHARACTERS": "Last name can't contain special characters & numbers.",
    "ERROR_EMPTY_ARTISTIC_NAME": "Artist name not provived.",
    "ERROR_ARTISTIC_NAME_ALREADY_EXISTS": "Artistic name already exists.",

    "ERROR_MAX_LENGTH_FIRST_NAME": "First name's size can't be longer than 30 characters",
    "ERROR_MAX_LENGTH_LAST_NAME": "Las name's size can't be longer than 150 characters",
    "ERROR_NOT_LOGGED_IN": "You must be logged in to do this action.",
    "ERROR_NOT_AN_ARTIST": "You are not an artist, and therefore you cannot be here.",
    "ERROR_NO_ARTIST_FOUND": "The artist you are searching for does not exist.",
    "ERROR_OFFER_NOT_OWNED": "This offer is not yours.",
    "ERROR_OFFER_NOT_FOUND": "The offer you are searching for does not exist.",
    "ERROR_NO_DATA_GIVEN": "The form has no data.",
    "ERROR_NO_MATCHING_LANGUAGE": "The language you want is not available.",
    "ERROR_ACTOR_NOT_FOUND": "The actor you are searching does not exist.",
    "ERROR_NO_GIVEN_LANGUAGE": "You must give a language to switch to."

}


def translate(key_language: str, key_to_translate: str):
    translations = {
        "es": spanish,
        "en": english
    }

    return {"error": translations[key_language][key_to_translate]}
