# Generated by Django 2.1.7 on 2019-03-24 12:21

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('paypalAccount', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtisticGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('parentGender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grooving.ArtisticGender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(3000)])),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=366)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('minimumPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('paypalAccount', models.CharField(blank=True, max_length=255, null=True)),
                ('holder', models.CharField(max_length=255)),
                ('expirationDate', models.DateField()),
                ('number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('priceHour', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('NEGOTIATION', 'NEGOTIATION'), ('CONTRACT_MADE', 'CONTRACT_MADE'), ('WITHDRAWN', 'WITHDRAWN'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED'), ('PAYMENT_MADE', 'PAYMENT_MADE')], max_length=20)),
                ('date', models.DateTimeField()),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('paymentCode', models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ('eventLocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Grooving.EventLocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('appliedVAT', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('custom', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grooving.Custom')),
                ('fare', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grooving.Fare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('info', models.TextField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('artisticName', models.CharField(blank=True, max_length=140, null=True)),
                ('artisticGender', models.ManyToManyField(blank=True, to='Grooving.ArtisticGender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('PHOTO', 'PHOTO'), ('DESCRIPTION', 'DESCRIPTION'), ('VIDEO', 'VIDEO'), ('AUDIO', 'AUDIO'), ('SOCIAL', 'SOCIAL'), ('MEMBER', 'MEMBER')], max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('portfolioModule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Grooving.Portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('minimumPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('paypalTax', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('creditCardTax', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('profit', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('logo', models.CharField(max_length=255)),
                ('appName', models.CharField(max_length=255)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('termsText', models.TextField(null=True)),
                ('privacyText', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('parentZone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grooving.Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='zone',
            field=models.ManyToManyField(blank=True, to='Grooving.Zone'),
        ),
        migrations.AddField(
            model_name='paymentpackage',
            name='performance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grooving.Performance'),
        ),
        migrations.AddField(
            model_name='paymentpackage',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grooving.Portfolio'),
        ),
        migrations.AddField(
            model_name='offer',
            name='paymentPackage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grooving.PaymentPackage'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grooving.Zone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='eventLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grooving.EventLocation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grooving.Portfolio'),
        ),
        migrations.AddField(
            model_name='artist',
            name='portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grooving.Portfolio'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
