# Generated by Django 2.1.7 on 2019-03-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grooving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='eventLocation',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='paymentPackage',
        ),
    ]
